### ISSUE TITLE
Handle multi-choice answers

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#15]
How do we expect the CSV cells' values to look when they correspond to a multi-choice answer?

Eg, if someone wants to provide an attendee's country in the CSV, how will they do that?
They'll have a column with the header "country" or something like that, and what value? "US"? "United Stated"? (I'm inclined to try both).

Another eg, if someone wants to provide the attendee's state in the CSV, how will they do that?
Have a column labelled "state", and the value needs to either be the state's full name (and hope it matches a state that's in our DB), or the state's abbreviation (and again hope it matches what's in our DB), or a state ID (and again hope it matches what's in our DB). (I'm inclined to try all 3, and if we can't determine which, give an error. When we add data preview, it would be good to scan for these errors or something.)

Last eg, if someone has a custom question in EE, which accepts values of either "large", "medium" or "small", how should they provide that in the CSV? Is it just up to them to make sure the CSV's values match what's acceptable for the question? (For the MVP I'm inclined to say yes, it's just up to them to make sure they match; possibly post MVP we could scan the entire column for all its values, and ask them to map the cells' values to acceptable question options.)

**Comment by mnelson4** [comment]
@tn3rb do you have any MVP suggestions? (We can record more elaborate suggestions too, but I'd like to sticking to implementing MVP solutions for the initial BETA)

**Comment by mnelson4** [comment]
> Another eg, if someone wants to provide the attendee's state in the CSV, how will they do that?

That's actually been resolved. They can use the state ID, abbreviation, or name. Same goes for countries.

**Comment by tn3rb** [comment]
oh sry I missed this issue Michael, I'm not in the habit of looking through the "New Issues" pipeline for things assigned to me. Always better to ping me in chat if you need feedback from me.

re:

> if someone wants to provide an attendee's country in the CSV, how will they do that?
> if someone wants to provide the attendee's state in the CSV, how will they do that?
> ...
> I'm inclined to try all 3, and if we can't determine which, give an error. 

ya I'm more inclined to just do what's best an not opt for a stripped down MVP since that does not seem to ever be what we really truly support as an organization. ie: it appears to me that our culture is more about doing things properly right from the start (when it is obvious) as opposed to pushing out some obviously janky MVP solution.

> if someone has a custom question in EE, which accepts values of either "large", "medium" or "small", how should they provide that in the CSV?

as already discussed on #24 I think using pipes is the better solution for the following reasons:

- it's less likely to conflict with data in the CSV itself
- it's what EE3 users are already used to doing and therefore requires no retraining
- that solution may be a hard learned lesson from EE3 that we should not ignore

**Comment by mnelson4** [comment]
fixed by #24
