### ISSUE TITLE
Add payments

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#17]
## Issue Overview

The EE3 importer supported creating payments based on "payment status" and "amount paid" columns. So far, we're not. 
Shall we also support a "payment status" column (whose value can be one of the payment stati), and a "payment amount" column (whose value is a float)?
If not supplied, we'll probably default to having a payment equal to the transaction total; or have question (on the "select event" page; which could probably renamed to "other details" or something) asking for what the user would like the default payment status to be. (Similarly, we could ask for default transaction and registration stati.)
I kinda think I should spend a couple hours on this for the MVP, and so how much of that I manage to accomplish. Thoughts @joshfeck ?

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by joshfeck** [comment]
A payment amount column would be useful, it could map to `esp_registration_payment.RPY_amount`.

I'm inclined to not offer a payment status column. If they've entered an amount for the payment, then we'll add a payment record to the db and its STS_ID will be PAP. If they don't have an amount for payment, then no need to record a payment.

Same for transaction status. I think for the MVP the transaction status related to anything imported should be TCM. 

With regards to defaults, since the event will already be created and the event will have a default registration status set in the even options, the importer could use what's set there. In other words, no need to add another option to the importer for this. 

If the event's default reg. status is Pending payment, and no payment amount is provided in the import data row, then the reg status will be Pending Payment. If a payment amount is provided, then the reg status will be Approved.

An event where the ticket price is 0.00 should have automatic RAP reg status for imported attendees. The same would also be true for an event where the default reg status is Approved, regardless of ticket price or payment.

**Comment by mnelson4** [comment]
Great points, thanks. Yes I’ll try to apply those and then give an update.

**Comment by mnelson4** [comment]
Hmmm, one item I forgot to think about: payment method. Should we ask for a default payment method during event selection (which will be the first step), or on a new step, or at the bottom of the mapping step?

**Comment by mnelson4** [comment]
Or just use "other" payment method?

**Comment by joshfeck** [comment]
I don't think we need a payment method, we could probably just put "other". Once we're past MVP maybe we could do a column so they can map a csv column so each registration can have a different payment method.

**Comment by mnelson4** [comment]
the related PR is merged into master, but this is a good testing checklist for before release
