### ISSUE TITLE
Pretty up button where we choose the importer

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-attendee-importer#18]
## Issue Overview

Right now, the button to select the attendee CSV importer is pretty ugly (see https://drive.google.com/a/eventespresso.com/file/d/1moA6Kd4ns9F5VHeMJAMK2tZPBgS4VZjq/view?usp=drivesdk). Also, we talked about having a link to the importer located elsewhere (like in the registration list table), and I thought about adding it to the WP importer page.
Thoughts?

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by joshfeck** [comment]
Can you make it so when you click the navigation item under Event Espresso > Add-ons, it goes directly to step 1? I don't think there should be a page in between that just has a link to click on. 

With regards to adding navigation from other places like Event Espresso > Registrations or Tools > Import, I don't think we should add those. It should be fine to just have the one navigation item that's already under Event Espresso > Add-ons.

**Comment by tn3rb** [comment]
Eventually we will have multiple importers to choose from, so maybe those can only be displayed when there is more than one option to choose from?

**Comment by tn3rb** [comment]
One other issue I thought of that might change how the form steps are laid out, is that we should maybe have the admin choose the event and ticket first, because that will change what questions are available for the system.

As it is now, you connect the CSV columns with questions before choosing the event. This means we are loading EVERY QUESTION in the db, whereas they likely only need to see the questions for that specific event. Having them choose the event first means that we could only query for those questions, which will make the process of connecting them to CSV columns much easier.

**Comment by joshfeck** [comment]
> Eventually we will have multiple importers to choose from, so maybe those can only be displayed when there is more than one option to choose from?

Or we just add more items under Event Espresso > Add-ons. e.g. an Event Importer add-on will add an "Event Importer" menu item under Event Espresso > Add-ons.

**Comment by mnelson4** [comment]
I'm fine with either approach TBH. Brent's approach allows for having an image and description of the job, although it's possible those are unnecessary. @tn3rb wdyt?

**Comment by mnelson4** [comment]
Oh and I moved Brent's other suggestion to another issue: https://github.com/eventespresso/eea-attendee-importer/issues/20

**Comment by tn3rb** [comment]
> having an image and description of the job, although it's possible those are unnecessary

those could be nice additions to the UI. I can help make it all look pretty when the time comes

**Comment by joshfeck** [comment]
OK then, but does it make sense to have the "Attendee Import" menu item when that menu item is actually going to be for other import tools?

I do think the extra page in the UI could be eliminated in this case because admin menu nav item can do the job of getting the user to the page that starts the attendee import process.

**Comment by mnelson4** [comment]
> OK then, but does it make sense to have the "Attendee Import" menu item when that menu item is actually going to be for other import tools?

Yeah if we left this importer selection page, we'd rename it to just importer.

But I'm leaning towards removing the importer selection page. Less is better IMO. I'm inclined to just add importers to the menu, not have a page dedicated to it. The descriptions and images, so far, seem unnecessary; just a name is enough to convey what the importer will do.
So Brent, if you're ok with it, I'll just skip the importer selection page, and instead just add a menu item for each importer available.

**Comment by tn3rb** [comment]
let's just go with the addons menu item then and drop the page.
if at some point in the future we end up with a whole whack of importers and want to clean up the admin menu, then we can consolidate everything onto one page.
